<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href=Sun_Dec_31_22_57_13_IST_2017.jpg target="_blank">Screenshot captured</a>]]>
    </line>
    <line>
      <![CDATA[</br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Dec_31_22_57_13_IST_2017.jpg target="_blank"><img src=Sun_Dec_31_22_57_13_IST_2017.jpg height=200 width=400></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Dec_31_22_57_17_IST_2017.jpg target="_blank">Screenshot captured</a>]]>
    </line>
    <line>
      <![CDATA[</br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Dec_31_22_57_17_IST_2017.jpg target="_blank"><img src=Sun_Dec_31_22_57_17_IST_2017.jpg height=200 width=400></a>]]>
    </line>
  </reporter-output>
  <suite name="DataDrivenFramework" duration-ms="4048" started-at="2017-12-31T17:27:13Z" finished-at="2017-12-31T17:27:17Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="598" started-at="2017-12-31T17:27:13Z" finished-at="2017-12-31T17:27:13Z">
      <class name="testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:testcases.BankManagerLoginTest@58c1670b]" name="loginAsBankManager" duration-ms="332" started-at="2017-12-31T22:57:13Z" finished-at="2017-12-31T22:57:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Dec_31_22_57_13_IST_2017.jpg target="_blank">Screenshot captured</a>]]>
            </line>
            <line>
              <![CDATA[</br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Dec_31_22_57_13_IST_2017.jpg target="_blank"><img src=Sun_Dec_31_22_57_13_IST_2017.jpg height=200 width=400></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="3427" started-at="2017-12-31T17:27:13Z" finished-at="2017-12-31T17:27:17Z">
      <class name="testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.AddCustomerTest@a38d7a3]" name="setUp" is-config="true" duration-ms="10634" started-at="2017-12-31T22:57:02Z" finished-at="2017-12-31T22:57:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="addCustomer()[pri:0, instance:testcases.AddCustomerTest@a38d7a3]" name="addCustomer" duration-ms="3242" started-at="2017-12-31T22:57:13Z" finished-at="2017-12-31T22:57:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[customer not added successfully expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: customer not added successfully expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Dec_31_22_57_17_IST_2017.jpg target="_blank">Screenshot captured</a>]]>
            </line>
            <line>
              <![CDATA[</br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Dec_31_22_57_17_IST_2017.jpg target="_blank"><img src=Sun_Dec_31_22_57_17_IST_2017.jpg height=200 width=400></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.AddCustomerTest@a38d7a3]" name="tearDown" is-config="true" duration-ms="816" started-at="2017-12-31T22:57:17Z" finished-at="2017-12-31T22:57:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- DataDrivenFramework -->
</testng-results>
